### ISSUE TITLE
Game crash after receiving too many packets at a time

### ISSUE THREAD

**Issue by Ranzeplay** [Ranzeplay/InstantMarker#2]
When holding the marking key, the client may crash. Error message as follows:

```
java.util.ConcurrentModificationException
	at java.base/java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1013)
	at java.base/java.util.ArrayList$Itr.next(ArrayList.java:967)
	at me.ranzeplay.instantmarker.client.hud.MarkerRenderer.drawEveryTick(MarkerRenderer.java:16)
	at net.minecraft.class_329.handler$ceo000$onGameOverlayPost(class_329.java:3486)
	at net.minecraft.class_329.method_1753(class_329.java:394)
	at net.minecraft.class_757.method_3192(class_757.java:862)
	at net.minecraft.class_310.method_1523(class_310.java:1176)
	at net.minecraft.class_310.method_1514(class_310.java:767)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:58)
	at oolloo.jlw.Wrapper.main(Wrapper.java:51)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.base/java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1013)
	at java.base/java.util.ArrayList$Itr.next(ArrayList.java:967)
	at me.ranzeplay.instantmarker.client.hud.MarkerRenderer.drawEveryTick(MarkerRenderer.java:16)
	at net.minecraft.class_329.handler$ceo000$onGameOverlayPost(class_329.java:3486)
	at net.minecraft.class_329.method_1753(class_329.java:394)

-- Affected level --
Details:
	All players: 2 total; [class_746['xxx'/651740, l='ClientLevel', x=-50.05, y=70.94, z=-172.47], class_745['xxx'/644532, l='ClientLevel', x=-57.13, y=70.00, z=-171.19]]
	Chunk stats: 1024, 613
	Level dimension: minecraft:overworld
	Level spawn location: World: (-256,63,-176), Section: (at 0,15,0 in -16,3,-11; chunk contains blocks -256,-64,-176 to -241,319,-161), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,-64,-512 to -1,319,-1)
	Level time: 566433420 game time, 574191231 day time
	Server brand: fabric
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:453)
	at net.minecraft.class_310.method_1587(class_310.java:2338)
	at net.minecraft.class_310.method_1514(class_310.java:791)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:58)
	at oolloo.jlw.Wrapper.main(Wrapper.java:51)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Fabric Mods

```

**Comment by Ranzeplay** [comment]
We will add a lock to the marker list.
